export const APP_CONFIG = {
  name: 'Inventra',
  tagline: "Inventra.AI — Find What's Near You.",
  description: 'See which shop near you has what you need — right now.',
  version: '2.4.0',
  defaultRadiusMiles: 2.0,
  itemsPerPage: 6,
};

export const NAV_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Shops', href: '/#shops' },
  { name: 'Dashboard', href: '/dashboard' },
  { name: 'Admin', href: '/admin' },
  { name: 'Profile', href: '/profile' },
  { name: 'Settings', href: '/settings' },
];

export const CATEGORIES_LIST = [
  'All',
  'Bath & Body',
  'Hair',
  'Skin & Face',
  'Beauty & Cosmetics',
  'Feminine Hygiene',
  'Baby Care',
  'Health & Pharma',
  'Sexual Wellness',
  'Vegetables & Fruits',
  'Atta, Rice & Dal',
  'Oil, Ghee & Masala',
  'Dairy, Bread & Eggs',
  'Bakery & Biscuits',
  'Dry Fruits & Cereals',
  'Chicken, Meat & Fish',
  'Kitchenware & Appliances',
  'Chips & Namkeen',
  'Sweets & Chocolates',
  'Drinks & Juices',
  'Tea, Coffee & Milk Drinks',
  'Instant Food',
  'Sauces & Spreads',
  'Paan Corner',
  'Ice Creams & More',
  'Home & Lifestyle',
  'Cleaners & Repellents',
  'Electronics',
  'Stationery & Games',
  'Stores',
  'E-Cards',
] as const;

export const DEFAULT_LOCATIONS = [
  'Tadikonda, Andhra Pradesh',
  'Guntur Main City, AP',
  'Vijayawada Central, AP',
  'Mangalagiri, AP',
  'Tenali Town, AP',
  'Amaravati Capital Region, AP',
  'Hyderabad, Telangana',
  'Visakhapatnam, AP',
  'Bengaluru, Karnataka',
];
